#!/bin/bash
# https://www.youtube.com/watch?v=hwrnmQumtPw
# interpreter # to use for the script
# chmod 755 scandir
myname=$(whoami)

cd "/home/user/Desktop/d/linux/mogli"
echo "Hello world user = "  "$myname"
 
for i in * .*;
do
    
    echo "Handling $i"
done

 

#ls -l
