#!/bin/bash

clear
sudo ifconfig
echo "-------------------------"
sudo iwconfig
echo "-------------------------"
sudo /usr/sbin/airmon-ng 


# port="wlp1s0"
# monport="wlp1s0mon"  
port="wlxe894f6236dc9"
monport="wlan0mon"   

echo "[1]:airmon-ng check kill"
sudo airmon-ng check kill

echo "[2]: airmon-ng start $port"
sudo airmon-ng start $port # Start monitoring $port
sudo /usr/sbin/airmon-ng 

echo "[3]: sudo airodump-ng $monport -w handshakes -b abg"
  
sudo airodump-ng $monport -w handshakes -b abg
 
 Launching Terminator terminator
 Split Horizontally: Ctrl + Shift + O
 Split Vertically:    Ctrl + Shift + E
Customization: right-click
 

phy0	wlp1s0		iwlwifi		Intel Corporation Wireless 8260 (rev 3a)
phy1	wlxe894f6236dc9	rt2800usb	Ralink Technology, Corp. RT2870/RT3070
 
 
