#!/bin/bash

clear
sudo ifconfig
echo "-------------------------"
sudo iwconfig
echo "-------------------------"
sudo /usr/sbin/airmon-ng 

port="wlp1s0"
monport="wlp1s0mon"  

echo "[1]:airmon-ng check kill"
sudo airmon-ng check kill

echo "[2]: airmon-ng start $port"
sudo airmon-ng start $port # Start monitoring $port
sudo /usr/sbin/airmon-ng 

echo "[3]: sudo airodump-ng $monport -w handshakes -b abg"
  
sudo airodump-ng $monport -w handshakes -b abg
 
 Launching Terminator terminator
 Split Horizontally: Ctrl + Shift + O
 Split Vertically:    Ctrl + Shift + E
Customization: right-click
 
echo  " in terminal 2 rename to scan1wifi run ./scan1wifi"
echo "  in terminal 3 rename to discon   run ./disconn
 
 
