#!/bin/bash

clear
ifconfig
echo "-------------------------"
iwconfig
echo "-------------------------"
 
#port="wlp1s0"
#monport="wlp1s0mon"

# parrot
#port="wlx940c6d87e5cc"
#monport="wlan0mon" 

#unbunto
port="wlx940c6d87e5cc"    
monport="wlxe894f6236dca" 



echo "[1]:airmon-ng check kill"
sudo airmon-ng check kill

echo "[2]: airmon-ng start $port"
sudo airmon-ng start $port # Start monitoring $port

echo "[3]: airodump-ng $monport -w capture"
  
sudo airodump-ng $monport -w capture
sudo /usr/sbin/airmon-ng 
echo "[4]: besside-ng $monport"
sudo besside-ng $monport

#echo "[5]: airmon-ng stop $monport # Stop monitor"
#Stop monitor status and return to manger status
#sudo airmon-ng stop $monport

 
